import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ko' | 'en' | 'th';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('ko');

  // 로컬 스토리지에서 언어 설정 불러오기
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['ko', 'en', 'th'].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['ko'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// 번역 데이터
const translations = {
  ko: {
    // 헤더
    'nav.features': '기능',
    'nav.howItWorks': '작동 방식',
    'nav.contact': '연락처',
    
    // 메인 제목
    'hero.title.smart': '스마트 물류',
    'hero.title.sustainable': '지속 가능한 미래를 위한',
    'hero.subtitle': 'AI 기반의 지능형 화물 및 차량 매칭을 통해 빈 운행을 없애고, 경로를 최적화하며, 물류 비용을 절감합니다',
    
    // 사용자 포털
    'portal.driver.title': '운전자 포털',
    'portal.driver.description': '차량 관리, 최적 경로 찾기, 수익 극대화',
    'portal.driver.button': '운전자 대시보드',
    'portal.shipper.title': '화주 포털', 
    'portal.shipper.description': '화물 등록, 신뢰할 수 있는 운전자 찾기, 배송 추적',
    'portal.shipper.button': '화주 대시보드',
    'portal.admin.title': '관리자 포털',
    'portal.admin.description': '운영 모니터링, 데이터 분석, 플랫폼 관리',
    'portal.admin.button': '관리자 대시보드',
    
    // 통계
    'stats.emptyTrip': '빈 운행 감소',
    'stats.costSavings': '비용 절약',
    'stats.routeEfficiency': '경로 효율성',
    'stats.userSatisfaction': '사용자 만족도',
    
    // 기능 섹션
    'features.title': '플랫폼 기능',
    'features.subtitle': '화물 운송의 모든 측면을 최적화하도록 설계된 종합 물류 솔루션',
    'features.smartMatching.title': '스마트 차량 매칭',
    'features.smartMatching.description': 'AI 기반 알고리즘이 실시간으로 화물과 최적 차량 및 경로를 매칭합니다',
    'features.loadManagement.title': '효율적인 화물 관리',
    'features.loadManagement.description': '빈 공간을 공유하고 화물 적재를 최적화하여 차량 활용도를 극대화합니다',
    'features.realTimeTracking.title': '실시간 추적',
    'features.realTimeTracking.description': 'GPS 기반 모니터링과 실시간 업데이트, 도착 예정 시간 알림 및 배송 상태 제공',
    'features.dataInsights.title': '데이터 기반 인사이트',
    'features.dataInsights.description': '정보에 기반한 물류 의사결정을 위한 종합적인 분석 및 보고서',
    'features.userCentric.title': '사용자 중심 설계',
    'features.userCentric.description': '운전자, 화주, 물류 조정자를 위해 설계된 직관적인 인터페이스',
    'features.secureTrans.title': '안전한 거래',
    'features.secureTrans.description': '자동 정산 및 거래 내역을 갖춘 투명한 결제 시스템',
    
    // 작동 방식
    'howItWorks.title': '작동 방식',
    'howItWorks.subtitle': '화물 등록부터 배송 완료까지의 간단하고 효율적인 프로세스',
    'howItWorks.step1.title': '등록 또는 찾기',
    'howItWorks.step1.description': '화주는 화물을 등록하고, 운전자는 기회를 찾습니다',
    'howItWorks.step2.title': '스마트 매칭',
    'howItWorks.step2.description': 'AI 알고리즘이 최적의 화물-차량 매칭을 찾습니다',
    'howItWorks.step3.title': '추적 및 모니터링',
    'howItWorks.step3.description': '실시간 GPS 추적 및 상태 업데이트',
    'howItWorks.step4.title': '완료 및 결제',
    'howItWorks.step4.description': '자동 정산 및 평가 시스템',
    
    // 푸터
    'footer.description': '지능형 매칭과 최적화를 통해 스마트하고 지속 가능한 물류의 미래를 구축합니다.',
    'footer.platform': '플랫폼',
    'footer.features': '기능',
    'footer.contact': '연락처',
    'footer.support': '24/7 지원 가능',
    'footer.copyright': '2024 LogiShare. 모든 권리 보유. 현대적인 물류를 염두에 두고 제작되었습니다.',
    'driver.dashboard.title': '운전자 대시보드',
    'driver.dashboard.welcome': '다시 오신 것을 환영합니다, {name}',
    'driver.dashboard.online': '온라인',
    'driver.dashboard.updateLocation': '위치 업데이트',
    'driver.stats.earnings': '이번 주 수익',
    'driver.stats.completedTrips': '완료 운행',
    'driver.stats.avgRating': '평균 평점',
    'driver.stats.efficiency': '효율 점수',
    'driver.currentTrip': '현재 운행',
    'driver.tripId': '운행 ID',
    'driver.inTransit': '운송 중',
    'driver.pickup': '출발지',
    'driver.delivery': '도착지',
    'driver.progress': '진행률',
    'driver.eta': '도착 예정',
    'driver.smartMatches': '위치와 선호도 기반 스마트 매칭',
    'driver.urgent': '긴급',
    'driver.match': '매칭',
    'driver.vehicle': '차량',
    'driver.capacity': '적재 용량',
    'driver.currentLoad': '현재 적재',
    'driver.availableSpace': '가용 공간',
    'driver.updateVehicleInfo': '차량 정보 수정',
    'driver.newHighPriorityLoad': '새 고우선순위 화물',
    'driver.premiumRateAvailable': '프리미엄 요금 적용 구간',
    'driver.paymentForTrip': '운행 결제 완료',
    'driver.maintenanceReminder': '정비 알림',
    'driver.nextServiceDue': '2,500마일 후 정비 필요',
    'driver.availableLoads': '추천 화물',
    'driver.vehicleStatus': '차량 상태',
    'driver.notifications': '알림',
    'driver.quickActions': '빠른 작업',
    'driver.navigate': '경로 안내',
    'driver.updateStatus': '상태 업데이트',
    'driver.acceptLoad': '화물 수락',
    'driver.details': '상세',
    'driver.setAvailableHours': '운행 가능 시간 설정',
    'driver.updatePreferredRoutes': '선호 경로 업데이트',
    'driver.viewRatingReviews': '평점 및 리뷰 보기',
    'driver.earningsReport': '수익 보고서',

    'shipper.dashboard.title': '화주 대시보드',
    'shipper.dashboard.welcome': '다시 오신 것을 환영합니다, {name}',
    'shipper.dashboard.postNewLoad': '신규 화물 등록',
    'shipper.dashboard.findDrivers': '운전자 찾기',
    'shipper.stats.activeShipments': '진행 중 화물',
    'shipper.stats.thisMonthCost': '이번 달 비용',
    'shipper.stats.onTimeDelivery': '정시 배송률',
    'shipper.stats.avgSavings': '평균 절감률',
    'shipper.postNewLoad': '신규 화물 등록',
    'shipper.fillDetails': '화물 정보를 입력하세요',
    'shipper.cargoType': '화물 종류',
    'shipper.selectCargoType': '화물 종류 선택',
    'shipper.electronics': '전자제품',
    'shipper.autoParts': '자동차 부품',
    'shipper.foodProducts': '식품',
    'shipper.furniture': '가구',
    'shipper.other': '기타',
    'shipper.weight': '중량(파운드)',
    'shipper.weightPlaceholder': '예: 15000',
    'shipper.pickupLocation': '출발지',
    'shipper.deliveryLocation': '도착지',
    'shipper.cityState': '도시, 주',
    'shipper.pickupDate': '출발일',
    'shipper.deliveryDate': '도착일',
    'shipper.specialRequirements': '특이사항',
    'shipper.specialRequirementsPlaceholder': '온도, 파손주의 등',
    'shipper.budgetRange': '예산 범위',
    'shipper.budgetPlaceholder': '예: $1200-1500',
    'shipper.priorityLevel': '우선순위',
    'shipper.selectPriority': '우선순위 선택',
    'shipper.standard': '일반',
    'shipper.urgent': '긴급',
    'shipper.express': '특급',
    'shipper.postLoadAndFindMatches': '화물 등록 및 매칭 찾기',
    'shipper.cancel': '취소',
    'shipper.activeShipments': '진행중인 화물',
    'shipper.filter': '필터',
    'shipper.from': '출발',
    'shipper.to': '도착',
    'shipper.trackLive': '실시간 추적',
    'shipper.contactDriver': '기사 연락',
    'shipper.details': '상세',
    'shipper.availableDrivers': '가용 기사',
    'shipper.topMatchedDrivers': '최적 매칭 기사',
    'shipper.vehicleType': '차량 종류',
    'shipper.capacity': '적재 용량',
    'shipper.match': '매칭',
    'shipper.available': '가용',
    'shipper.bookDriver': '기사 예약',
    'shipper.viewProfile': '프로필 보기',
    'shipper.recentActivity': '최근 활동',
    'shipper.deliveryCompleted': '배송 완료',
    'shipper.loadPickedUp': '화물 픽업',
    'shipper.newDriverMatch': '새 기사 매칭',
    'shipper.postEmergencyLoad': '긴급 화물 등록',
    'shipper.searchAvailableDrivers': '가용 기사 검색',
    'shipper.viewBillingHistory': '결제 내역',
    'shipper.rateRecentDrivers': '기사 평가',
    'shipper.costSavings': '비용 절감',
    'shipper.savedThisMonth': '이번 달 절감액',
    'shipper.averageSavings': '평균 23% 절감',

    'admin.dashboard.title': '관리자 대시보드',
    'admin.dashboard.overview': '플랫폼 개요 및 관리',
    'admin.stats.activeDrivers': '활성 운전자',
    'admin.stats.activeShippers': '활성 화주',
    'admin.stats.dailyShipments': '일일 배송',
    'admin.stats.platformRevenue': '플랫폼 수익',
    'admin.revenueAnalytics.title': '수익 분석',
    'admin.revenueAnalytics.description': '플랫폼 수익 및 성장 추이',
    'admin.revenueAnalytics.chartTitle': '수익 차트',
    'admin.revenueAnalytics.chartDescription': '대시보드 분석 시각화',
    'admin.revenueAnalytics.thisMonth': '이번 달',
    'admin.revenueAnalytics.lastMonth': '지난 달',
    'admin.revenueAnalytics.growth': '성장률',
    'admin.recentTransactions.title': '최근 거래',
    'admin.recentTransactions.description': '최신 플랫폼 재무 활동',
    'admin.recentTransactions.id': 'ID',
    'admin.topPerformingRoutes.title': '상위 운행 경로',
    'admin.topPerformingRoutes.description': '가장 수익성 높고 활발한 배송 경로',
    'admin.topPerformingRoutes.shipments': '건',
    'admin.topPerformingRoutes.efficiency': '효율',
    'admin.systemStatus.title': '시스템 상태',
    'admin.systemStatus.apiStatus': 'API 상태',
    'admin.systemStatus.database': '데이터베이스',
    'admin.systemStatus.paymentGateway': '결제 게이트웨이',
    'admin.systemStatus.gpsTracking': 'GPS 추적',
    'admin.systemStatus.mobileApps': '모바일 앱',
    'admin.systemAlerts.title': '시스템 알림',
    'admin.platformManagement.title': '플랫폼 관리',
    'admin.platformManagement.manageUsers': '사용자 관리',
    'admin.platformManagement.vehicleVerifications': '차량 인증',
    'admin.platformManagement.paymentSettings': '결제 설정',
    'admin.platformManagement.analyticsReports': '분석 리포트',
    'admin.platformManagement.systemMaintenance': '시스템 점검',
    'admin.performanceMetrics.title': '성과 지표',
    'admin.performanceMetrics.matchSuccessRate': '매칭 성공률',
    'admin.performanceMetrics.driverSatisfaction': '운전자 만족도',
    'admin.performanceMetrics.platformUptime': '플랫폼 가동률',
    'admin.driverPayment': '기사 결제',
    'admin.shipperCharge': '화주 청구',
    'admin.platformFee': '플랫폼 수수료',
    'admin.completed': '완료',
    'admin.pending': '대기',
    'admin.operational': '운영 중',
    'admin.healthy': '정상',
    'admin.connected': '연결됨',
    'admin.maintenance': '점검 중',
    'admin.online': '온라인',
  },
  en: {
    // 헤더
    'nav.features': 'Features',
    'nav.howItWorks': 'How it Works',
    'nav.contact': 'Contact',
    
    // 메인 제목
    'hero.title.smart': 'Smart Logistics for a',
    'hero.title.sustainable': 'Sustainable Future',
    'hero.subtitle': 'Eliminate empty trips, optimize routes, and reduce logistics costs through intelligent cargo and vehicle matching powered by AI',
    
    // 사용자 포털
    'portal.driver.title': 'Driver Portal',
    'portal.driver.description': 'Manage your vehicle, find optimal routes, and maximize earnings',
    'portal.driver.button': 'Driver Dashboard',
    'portal.shipper.title': 'Shipper Portal',
    'portal.shipper.description': 'Post loads, find reliable drivers, and track shipments',
    'portal.shipper.button': 'Shipper Dashboard',
    'portal.admin.title': 'Admin Portal',
    'portal.admin.description': 'Monitor operations, analyze data, and manage platform',
    'portal.admin.button': 'Admin Dashboard',
    
    // 통계
    'stats.emptyTrip': 'Empty Trip Reduction',
    'stats.costSavings': 'Cost Savings',
    'stats.routeEfficiency': 'Route Efficiency',
    'stats.userSatisfaction': 'User Satisfaction',
    
    // 기능 섹션
    'features.title': 'Platform Features',
    'features.subtitle': 'Comprehensive logistics solution designed to optimize every aspect of cargo transportation',
    'features.smartMatching.title': 'Smart Vehicle Matching',
    'features.smartMatching.description': 'AI-powered algorithm matches cargo with optimal vehicles and routes in real-time',
    'features.loadManagement.title': 'Efficient Load Management',
    'features.loadManagement.description': 'Maximize vehicle utilization by sharing empty space and optimizing cargo loads',
    'features.realTimeTracking.title': 'Real-time Tracking',
    'features.realTimeTracking.description': 'GPS-based monitoring with live updates, ETA notifications, and delivery status',
    'features.dataInsights.title': 'Data-Driven Insights',
    'features.dataInsights.description': 'Comprehensive analytics and reporting for informed logistics decisions',
    'features.userCentric.title': 'User-Centric Design',
    'features.userCentric.description': 'Intuitive interface designed for drivers, shippers, and logistics coordinators',
    'features.secureTrans.title': 'Secure Transactions',
    'features.secureTrans.description': 'Transparent payment system with automatic settlement and transaction history',
    
    // 작동 방식
    'howItWorks.title': 'How It Works',
    'howItWorks.subtitle': 'Simple, efficient process from load posting to delivery completion',
    'howItWorks.step1.title': 'Post or Find',
    'howItWorks.step1.description': 'Shippers post loads, drivers find opportunities',
    'howItWorks.step2.title': 'Smart Match',
    'howItWorks.step2.description': 'AI algorithm finds optimal cargo-vehicle matches',
    'howItWorks.step3.title': 'Track & Monitor',
    'howItWorks.step3.description': 'Real-time GPS tracking and status updates',
    'howItWorks.step4.title': 'Complete & Pay',
    'howItWorks.step4.description': 'Automatic settlement and rating system',
    
    // 푸터
    'footer.description': 'Building the future of smart, sustainable logistics through intelligent matching and optimization.',
    'footer.platform': 'Platform',
    'footer.features': 'Features',
    'footer.contact': 'Contact',
    'footer.support': '24/7 Support Available',
    'footer.copyright': '2024 LogiShare. All rights reserved. Built with modern logistics in mind.',
    'driver.dashboard.title': 'Driver Dashboard',
    'driver.dashboard.welcome': 'Welcome back, {name}',
    'driver.dashboard.online': 'Online',
    'driver.dashboard.updateLocation': 'Update Location',
    'driver.stats.earnings': 'This Week Earnings',
    'driver.stats.completedTrips': 'Completed Trips',
    'driver.stats.avgRating': 'Average Rating',
    'driver.stats.efficiency': 'Efficiency Score',
    'driver.currentTrip': 'Current Trip',
    'driver.tripId': 'Trip ID',
    'driver.inTransit': 'In Transit',
    'driver.pickup': 'Pickup',
    'driver.delivery': 'Delivery',
    'driver.progress': 'Progress',
    'driver.eta': 'ETA',
    'driver.smartMatches': 'Smart Matches Based on Location and Preference',
    'driver.urgent': 'Urgent',
    'driver.match': 'Match',
    'driver.vehicle': 'Vehicle',
    'driver.capacity': 'Capacity',
    'driver.currentLoad': 'Current Load',
    'driver.availableSpace': 'Available Space',
    'driver.updateVehicleInfo': 'Update Vehicle Info',
    'driver.newHighPriorityLoad': 'New High Priority Load',
    'driver.premiumRateAvailable': 'Premium Rate Available',
    'driver.paymentForTrip': 'Payment for Trip',
    'driver.maintenanceReminder': 'Maintenance Reminder',
    'driver.nextServiceDue': 'Next Service Due in 2,500 Miles',
    'driver.availableLoads': 'Available Loads',
    'driver.vehicleStatus': 'Vehicle Status',
    'driver.notifications': 'Notifications',
    'driver.quickActions': 'Quick Actions',
    'driver.navigate': 'Navigate',
    'driver.updateStatus': 'Update Status',
    'driver.acceptLoad': 'Accept Load',
    'driver.details': 'Details',
    'driver.setAvailableHours': 'Set Available Hours',
    'driver.updatePreferredRoutes': 'Update Preferred Routes',
    'driver.viewRatingReviews': 'View Rating & Reviews',
    'driver.earningsReport': 'Earnings Report',

    'shipper.dashboard.title': 'Shipper Dashboard',
    'shipper.dashboard.welcome': 'Welcome back, {name}',
    'shipper.dashboard.postNewLoad': 'Post New Load',
    'shipper.dashboard.findDrivers': 'Find Drivers',
    'shipper.stats.activeShipments': 'Active Shipments',
    'shipper.stats.thisMonthCost': 'This Month Cost',
    'shipper.stats.onTimeDelivery': 'On-Time Delivery',
    'shipper.stats.avgSavings': 'Avg Savings',

    'admin.dashboard.title': 'Admin Dashboard',
    'admin.dashboard.overview': 'Platform overview and management',
    'admin.stats.activeDrivers': 'Active Drivers',
    'admin.stats.activeShippers': 'Active Shippers',
    'admin.stats.dailyShipments': 'Daily Shipments',
    'admin.stats.platformRevenue': 'Platform Revenue',
    'admin.revenueAnalytics.title': 'Revenue Analytics',
    'admin.revenueAnalytics.description': 'Platform revenue and growth trends',
    'admin.revenueAnalytics.chartTitle': 'Revenue Chart',
    'admin.revenueAnalytics.chartDescription': 'Interactive analytics visualization',
    'admin.revenueAnalytics.thisMonth': 'This Month',
    'admin.revenueAnalytics.lastMonth': 'Last Month',
    'admin.revenueAnalytics.growth': 'Growth',
    'admin.recentTransactions.title': 'Recent Transactions',
    'admin.recentTransactions.description': 'Latest platform financial activity',
    'admin.recentTransactions.id': 'ID',
    'admin.topPerformingRoutes.title': 'Top Performing Routes',
    'admin.topPerformingRoutes.description': 'Most profitable and active shipping routes',
    'admin.topPerformingRoutes.shipments': 'shipments',
    'admin.topPerformingRoutes.efficiency': 'efficiency',
    'admin.systemStatus.title': 'System Status',
    'admin.systemStatus.apiStatus': 'API Status',
    'admin.systemStatus.database': 'Database',
    'admin.systemStatus.paymentGateway': 'Payment Gateway',
    'admin.systemStatus.gpsTracking': 'GPS Tracking',
    'admin.systemStatus.mobileApps': 'Mobile Apps',
    'admin.systemAlerts.title': 'System Alerts',
    'admin.platformManagement.title': 'Platform Management',
    'admin.platformManagement.manageUsers': 'Manage Users',
    'admin.platformManagement.vehicleVerifications': 'Vehicle Verifications',
    'admin.platformManagement.paymentSettings': 'Payment Settings',
    'admin.platformManagement.analyticsReports': 'Analytics Reports',
    'admin.platformManagement.systemMaintenance': 'System Maintenance',
    'admin.performanceMetrics.title': 'Performance Metrics',
    'admin.performanceMetrics.matchSuccessRate': 'Match Success Rate',
    'admin.performanceMetrics.driverSatisfaction': 'Driver Satisfaction',
    'admin.performanceMetrics.platformUptime': 'Platform Uptime',
  },
  th: {
    // 헤더
    'nav.features': 'คุณสมบัติ',
    'nav.howItWorks': 'วิธีการทำงาน',
    'nav.contact': 'ติดต่อ',
    
    // 메인 제목
    'hero.title.smart': 'โลจิสติกส์อัจฉริยะสำหรับ',
    'hero.title.sustainable': 'อนาคตที่ยั่งยืน',
    'hero.subtitle': 'กำจัดการเดินทางเปล่า เพิ่มประสิทธิภาพเส้นทาง และลดค่าใช้จ่ายโลจิสติกส์ผ่านการจับคู่สินค้าและยานพาหนะอัจฉริยะที่ขับเคลื่อนด้วย AI',
    
    // 사용자 포털
    'portal.driver.title': 'พอร์ทัลคนขับ',
    'portal.driver.description': 'จัดการยานพาหนะ หาเส้นทางที่เหมาะสม และเพิ่มรายได้สูงสุด',
    'portal.driver.button': 'แดชบอร์ดคนขับ',
    'portal.shipper.title': 'พอร์ทัลผู้ส่งสินค้า',
    'portal.shipper.description': 'โพสต์สินค้า หาคนขับที่เชื่อถือได้ และติดตามการจัดส่ง',
    'portal.shipper.button': 'แดชบอร์ดผู้ส่งสินค้า',
    'portal.admin.title': 'พอร์ทัลผู้ดูแลระบบ',
    'portal.admin.description': 'ติดตามการดำเนินงาน วิเคราะห์ข้อมูล และจัดการแพลตฟอร์ม',
    'portal.admin.button': 'แดชบอร์ดผู้ดูแลระบบ',
    
    // 통계
    'stats.emptyTrip': 'การลดการเดินทางเปล่า',
    'stats.costSavings': 'การประหยัดค่าใช้จ่าย',
    'stats.routeEfficiency': 'ประสิทธิภาพเส้นทาง',
    'stats.userSatisfaction': 'ความพึงพอใจของผู้ใช้',
    
    // 기능 섹션
    'features.title': 'คุณสมบัติของแพลตฟอร์ม',
    'features.subtitle': 'โซลูชันโลจิสติกส์ที่ครอบคลุมออกแบบมาเพื่อเพิ่มประสิทธิภาพทุกด้านของการขนส่งสินค้า',
    'features.smartMatching.title': 'การจับคู่ยานพาหนะอัจฉริยะ',
    'features.smartMatching.description': 'อัลกอริทึมที่ขับเคลื่อนด้วย AI จับคู่สินค้ากับยานพาหนะและเส้นทางที่เหมาะสมในเวลาจริง',
    'features.loadManagement.title': 'การจัดการสินค้าที่มีประสิทธิภาพ',
    'features.loadManagement.description': 'เพิ่มการใช้ประโยชน์จากยานพาหนะสูงสุดโดยการแบ่งปันพื้นที่ว่างและเพิ่มประสิทธิภาพการบรรทุกสินค้า',
    'features.realTimeTracking.title': 'การติดตามแบบเรียลไทม์',
    'features.realTimeTracking.description': 'การติดตามแบบ GPS พร้อมการอัปเดตสด การแจ้งเตือน ETA และสถานะการจัดส่ง',
    'features.dataInsights.title': 'ข้อมูลเชิงลึกที่ขับเคลื่อนด้วยข้อมูล',
    'features.dataInsights.description': 'การวิเคราะห์และรายงานที่ครอบคลุมสำหรับการตัดสินใจโลจิสติกส์ที่มีข้อมูลรองรับ',
    'features.userCentric.title': 'การออกแบบที่เน้นผู้ใช้',
    'features.userCentric.description': 'อินเทอร์เฟซที่ใช้งานง่ายที่ออกแบบมาสำหรับคนขับ ผู้ส่งสินค้า และผู้ประสานงานโลจิสติกส์',
    'features.secureTrans.title': 'การทำธุรกรรมที่ปลอดภัย',
    'features.secureTrans.description': 'ระบบการชำระเงินโปร่งใสพร้อมการชำระเงินอัตโนมัติและประวัติการทำธุรกรรม',
    
    // 작동 방식
    'howItWorks.title': 'วิธีการทำงาน',
    'howItWorks.subtitle': 'กระบวนการที่เรียบง่ายและมีประสิทธิภาพจากการโพสต์สินค้าจนถึงการจัดส่งเสร็จสิ้น',
    'howItWorks.step1.title': 'โพสต์หรือค้นหา',
    'howItWorks.step1.description': 'ผู้ส่งสินค้าโพสต์สินค้า คนขับหาโอกาส',
    'howItWorks.step2.title': 'การจับคู่อัจฉริยะ',
    'howItWorks.step2.description': 'อัลกอริทึม AI หาการจับคู่สินค้า-ยานพาหนะที่เหมาะสม',
    'howItWorks.step3.title': 'ติดตามและตรวจสอบ',
    'howItWorks.step3.description': 'การติดตาม GPS แบบเรียลไทม์และการอัปเดตสถานะ',
    'howItWorks.step4.title': 'เสร็จสิ้นและชำระเงิน',
    'howItWorks.step4.description': 'ระบบการชำระเงินอัตโนมัติและการให้คะแนน',
    
    // 푸터
    'footer.description': 'สร้างอนาคตของโลจิสติกส์อัจฉริยะและยั่งยืนผ่านการจับคู่และการเพิ่มประสิทธิภาพอัจฉริยะ',
    'footer.platform': 'แพลตฟอร์ม',
    'footer.features': 'คุณสมบัติ',
    'footer.contact': 'ติดต่อ',
    'footer.support': 'มีการสนับสนุน 24/7',
    'footer.copyright': '2024 LogiShare สงวนสิทธิ์ทั้งหมด สร้างขึ้นด้วยโลจิสติกส์สมัยใหม่',
    'driver.dashboard.title': 'แดชบอร์ดคนขับ',
    'driver.dashboard.welcome': 'ยินดีต้อนรับกลับมา, {name}',
    'driver.dashboard.online': 'ออนไลน์',
    'driver.dashboard.updateLocation': 'อัปเดตตำแหน่ง',
    'driver.stats.earnings': 'รายได้สัปดาห์นี้',
    'driver.stats.completedTrips': 'เที่ยวที่เสร็จสิ้น',
    'driver.stats.avgRating': 'คะแนนเฉลี่ย',
    'driver.stats.efficiency': 'คะแนนประสิทธิภาพ',
    'driver.currentTrip': 'เที่ยวปัจจุบัน',
    'driver.tripId': 'รหัสเที่ยว',
    'driver.inTransit': 'กำลังขนส่ง',
    'driver.pickup': 'จุดเริ่มการขนส่ง',
    'driver.delivery': 'จุดสิ้นสุดการขนส่ง',
    'driver.progress': 'ระยะทางที่เคลื่อนที่แล้ว',
    'driver.eta': 'เวลาที่คาดว่าจะถึง',
    'driver.smartMatches': 'การจับคู่ตามตำแหน่งและความชอบ',
    'driver.urgent': 'ด่วน',
    'driver.match': 'การจับคู่',
    'driver.vehicle': 'ยานพาหนะ',
    'driver.capacity': 'กำลังในการโอนย้าย',
    'driver.currentLoad': 'กำลังโอนย้ายที่มีอยู่',
    'driver.availableSpace': 'พื้นที่ที่ว่างเพียงพอ',
    'driver.updateVehicleInfo': 'อัปเดตข้อมูลยานพาหนะ',
    'driver.newHighPriorityLoad': 'นำความสำคัญสูงสุดนำมาโอนย้าย',
    'driver.premiumRateAvailable': 'อัตราค่าบริการครบครัว',
    'driver.paymentForTrip': 'การชำระเงินสำหรับเที่ยว',
    'driver.maintenanceReminder': 'การแจ้งเตือนการดูแล',
    'driver.nextServiceDue': 'ต้องดูแลระยะห่างถึงการดูแลครบครัวภายใน 2,500 ไมล์',
    'driver.availableLoads': 'งานที่แนะนำ',
    'driver.vehicleStatus': 'สถานะยานพาหนะ',
    'driver.notifications': 'การแจ้งเตือน',
    'driver.quickActions': 'การดำเนินการด่วน',
    'driver.navigate': 'นำทาง',
    'driver.updateStatus': 'อัปเดตสถานะ',
    'driver.acceptLoad': 'รับงาน',
    'driver.details': 'รายละเอียด',
    'driver.setAvailableHours': 'ตั้งเวลาว่าง',
    'driver.updatePreferredRoutes': 'อัปเดตเส้นทางที่ต้องการ',
    'driver.viewRatingReviews': 'ดูคะแนนและรีวิว',
    'driver.earningsReport': 'รายงานรายได้',

    'shipper.dashboard.title': 'แดชบอร์ดผู้ส่งสินค้า',
    'shipper.dashboard.welcome': 'ยินดีต้อนรับกลับมา, {name}',
    'shipper.dashboard.postNewLoad': 'โพสต์งานใหม่',
    'shipper.dashboard.findDrivers': 'ค้นหาคนขับ',
    'shipper.stats.activeShipments': 'งานที่กำลังดำเนินการ',
    'shipper.stats.thisMonthCost': 'ค่าใช้จ่ายเดือนนี้',
    'shipper.stats.onTimeDelivery': 'ส่งตรงเวลา',
    'shipper.stats.avgSavings': 'ออมเฉลี่ย',

    'admin.dashboard.title': 'แดชบอร์ดผู้ดูแลระบบ',
    'admin.dashboard.overview': 'ภาพรวมและการจัดการแพลตฟอร์ม',
    'admin.stats.activeDrivers': 'คนขับที่ใช้งานอยู่',
    'admin.stats.activeShippers': 'ผู้ส่งสินค้าที่ใช้งานอยู่',
    'admin.stats.dailyShipments': 'การจัดส่งรายวัน',
    'admin.stats.platformRevenue': 'รายได้แพลตฟอร์ม',
    'admin.revenueAnalytics.title': 'การวิเคราะห์รายได้',
    'admin.revenueAnalytics.description': 'แนวโน้มรายได้และการเติบโตของแพลตฟอร์ม',
    'admin.revenueAnalytics.chartTitle': 'แผนภูมิรายได้',
    'admin.revenueAnalytics.chartDescription': 'การแสดงผลวิเคราะห์แบบอินเทอร์แอคทีฟ',
    'admin.revenueAnalytics.thisMonth': 'เดือนนี้',
    'admin.revenueAnalytics.lastMonth': 'เดือนที่แล้ว',
    'admin.revenueAnalytics.growth': 'การเติบโต',
    'admin.recentTransactions.title': 'ธุรกรรมล่าสุด',
    'admin.recentTransactions.description': 'กิจกรรมทางการเงินล่าสุดของแพลตฟอร์ม',
    'admin.recentTransactions.id': 'รหัส',
    'admin.topPerformingRoutes.title': 'เส้นทางที่มีประสิทธิภาพสูงสุด',
    'admin.topPerformingRoutes.description': 'เส้นทางการจัดส่งที่ทำกำไรและใช้งานมากที่สุด',
    'admin.topPerformingRoutes.shipments': 'งาน',
    'admin.topPerformingRoutes.efficiency': 'ประสิทธิภาพ',
    'admin.systemStatus.title': 'สถานะระบบ',
    'admin.systemStatus.apiStatus': 'สถานะ API',
    'admin.systemStatus.database': 'ฐานข้อมูล',
    'admin.systemStatus.paymentGateway': 'เกตเวย์การชำระเงิน',
    'admin.systemStatus.gpsTracking': 'การติดตาม GPS',
    'admin.systemStatus.mobileApps': 'แอปมือถือ',
    'admin.systemAlerts.title': 'การแจ้งเตือนระบบ',
    'admin.platformManagement.title': 'การจัดการแพลตฟอร์ม',
    'admin.platformManagement.manageUsers': 'จัดการผู้ใช้',
    'admin.platformManagement.vehicleVerifications': 'การตรวจสอบยานพาหนะ',
    'admin.platformManagement.paymentSettings': 'การตั้งค่าการชำระเงิน',
    'admin.platformManagement.analyticsReports': 'รายงานการวิเคราะห์',
    'admin.platformManagement.systemMaintenance': 'บำรุงรักษาระบบ',
    'admin.performanceMetrics.title': 'ตัวชี้วัดประสิทธิภาพ',
    'admin.performanceMetrics.matchSuccessRate': 'อัตราความสำเร็จในการจับคู่',
    'admin.performanceMetrics.driverSatisfaction': 'ความพึงพอใจของคนขับ',
    'admin.performanceMetrics.platformUptime': 'เวลาทำงานของแพลตฟอร์ม',
    'admin.driverPayment': 'การชำระเงินคนขับ',
    'admin.shipperCharge': 'การคำนวณค่าบริการผู้ส่งสินค้า',
    'admin.platformFee': 'ค่าบริการพลตฟอร์ม',
    'admin.completed': 'เสร็จสิ้น',
    'admin.pending': 'รอดำเนินการ',
    'admin.operational': 'กำลังทำงาน',
    'admin.healthy': 'สภาพดี',
    'admin.connected': 'เชื่อมต่อแล้ว',
    'admin.maintenance': 'กำลังดูแล',
    'admin.online': 'ออนไลน์',
  }
};
